version: "3.9"


x-defaults: &x-defaults
  image: local
  build: .
  stdin_open: true
  tty: true
  depends_on:
    - postgres
    - rabbitmq


services:
  backend:
#    command: python ./app/manage.py runserver
    image: backend
    build: .
    container_name: backend
    ports:
      - "8000:8000"
      - "8001:8001"

    <<: *x-defaults

  celery:
    command: celery -A settings worker -l info --autoscale=0,10
    image: backend
    container_name: celery
    <<: *x-defaults

  celerybeat:
    command: celery -A settings beat -l info
    image: backend
    container_name: celerybeat
    <<: *x-defaults


  rabbitmq:
    image: rabbitmq:3.9.29-management
    container_name: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file: .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

  flower:
    image: mher/flower
    container_name: flower
    env_file: .env
    ports:
      - "5555:5555"
      - "5566:5566"
    command: celery --broker $CELERY_BROKER_URL flower
    depends_on:
      - rabbitmq
      - celery
      - celerybeat

volumes:
  db_data: {}
  pgadmin-data:

